### ISSUE TITLE
Upgraded to 2.0 and cant play music

### ISSUE THREAD

**Issue by andyofb** [mopidy/mopidy#1491]
As soon as I try and playback I get the following:

```
(<unknown>:42649): GStreamer-WARNING **: 0.10-style raw audio caps are being created. Should be audio/x-raw,format=(string).. now.
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
WARNING  Could not find a audio/x-raw-int decoder to handle media.
WARNING  GStreamer warning: gst-stream-error-quark: No decoder available for type 'audio/x-raw-int, endianness=(int)1234, channels=(int)2, width=(int)16, depth=(int)16, signed=(boolean)true, rate=(int)44100'. (6)
ERROR    GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
From cffi callback <function music_delivery at 0x109aa4500>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 992, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 109, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/playback.py", line 156, in music_delivery_callback
    timestamp=buffer_timestamp.get(), duration=duration)
TypeError: create_buffer() got an unexpected keyword argument 'capabilites'
```

**Comment by adamcik** [comment]
Please upgrade your mopidy-spotify version. Your are running an old version which does not work with Mopidy 2.0. The last mopidy-spotify release we did beofre mopidy 2.0 put in a version constraint to avoid this, but it seems you have an older version still.

**Comment by andyofb** [comment]
perfect. Thank you. I will try this
